### ISSUE TITLE
I have a problem Huston

### ISSUE THREAD

**Issue by ekkutlu** [TheDevFab/TradingView-Webhook-Bot#12]
Firs of all thanks for amazing bot but I have a some problem about running bot. Thanks for your help.

(TradingView-Webhook-Bot) root@CSVPS:~/twhook/TradingView-Webhook-Bot# python main.py
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    serve(app, host='0.0.0.0', port=80)
  File "/root/twhook/TradingView-Webhook-Bot/lib/python3.6/site-packages/waitress/__init__.py", line 12, in serve
    server = _server(app, **kw)
  File "/root/twhook/TradingView-Webhook-Bot/lib/python3.6/site-packages/waitress/server.py", line 88, in create_server
    sockinfo=sockinfo,
  File "/root/twhook/TradingView-Webhook-Bot/lib/python3.6/site-packages/waitress/server.py", line 239, in __init__
    self.bind_server_socket()
  File "/root/twhook/TradingView-Webhook-Bot/lib/python3.6/site-packages/waitress/server.py", line 368, in bind_server_socket
    self.bind(sockaddr)
  File "/root/twhook/TradingView-Webhook-Bot/lib/python3.6/site-packages/waitress/wasyncore.py", line 398, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use
(TradingView-Webhook-Bot) root@CSVPS:~/twhook/TradingView-Webhook-Bot#

**Comment by TheDevFab** [comment]
Hi,

The issue is that port 80 is already in use. I'd assume you also serve a website? Sadly TradingView only works on port 80 or 443.
